---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notes-secret
  namespace: dev
spec:
  encryptedData:
    DATABASE_URL: AgCM4q9YayNgHtE3Vf0+N+QIPaRNDH8ZrMIie05UWl61oSf6ZCdifAVSZPeV7/sS+0PY3F0+tKUJV/lnmoW7+56wDcHSnRqdeqvVCz6z63wO++XmE3BfE+lQt3vHnD8A/YO8muovKaAsRGAXAYdNIFFMkmZ92EEqeVRz2oaA6UfD+e0rZScs9W682JrgWDtqQOIZcyfUQc1o2sMuFg9kNP1kVOvWl5AgKJgJWLKFEcDcmeYYcPVNFWpCmw3jyUI+Sj4x0VGBf1dPfoGuMFQHaVO5Cf2lzJI3L7b8Remm3iuj/HxifI4eLjFWVeV42bGEMmj2HA1CgPuhryeKLn5Hl0AbxCk7OK2MX+Nziy8/H8OCFKyN98KBQ8LDFQmIoJkLklAnCGOk0FETt4B9ExrSB3JELJJ94Td9H3D+QeinHifd/gINMqO8SYKKQkxQl9EDObb3+4w4eEkrTcy4Z/Mh7V/Rgyx9DyMv+NDEG55AE6W/TvgbVDbmaudLIPn9LiUIUFD/VdcS739trgDanLp5XXI2Ilv2OQ72L5Xzm/JK/Mz+bIjlQeRXTnwTOrEgiOA0suMhh3155AEzP5wud967L6X1ZJC9KAy8o8mNPmjlogC9pkwqojwUdoDasvry07Gq5qxCNC8VAtiDNtUxS7Lp9h7XSedQMz6hNn+PKgs4sKrO1U0JlZjh3YRgc7R5t8BtclgxhW3c0GaWSjqdLNN/eVJ4Y3ea1qBO1fUXpGmWubyWyko3BLqMbAiwfe085wlGqZ2HpkJmH9VV8ZGD4Tn9WELdwtnqqHlGDHJDuz1UsJcOnpNT/OeMTINBS5L0EDBitnJuG3I1
    DB_SSL: AgCEKnYM7WxI6c7WuAUdPbY3lBM5N7VFCbRE8wUW4Fk+5XBGBeoFzpdgs5uzdX+UoJU+LhV/kd/WEW3qcEL8yZ6M2bYshNxiw9Bo4xJbkBkkWyFuOaBbsg9dVu3dgIhTXa6HMw429OhuEMgUipzqHyAY8Vq0MsgCJ6BblwJo7VDRPJ78VUPs89tP0rS4UNd9YcBR9u316R4WSJVQhC8RhKvj71x0tHvcweeqvBdi4V2y07pW7m0DxHrtnVYFzKWNgv1TCHS1qvnQLMaG1qR+nBE6Ro7pu8WadM00jD7M/huy3GZPRVnnzVgSacBu5PKvb+YTXXOTsRKhXfta5RcphgJ4SpWg/F2PNfwwTA7RQJDf1AFw3PfYVkEvA/hvbBw/vacQ9ht4bo7EAknuechorRDHGiqlWFnPUN19VTecyZXYC5lyvEYMlbBAQw6/U2esFFaBjfTmOB5Bpf5Zhlwvn3YNayLBnXx19Xf6b0WB68r7fCTK1697T10f//TFyv3qSSEfx+P2LIx/Ox6yQ+CjX1uKyF0ZujnaAIAtf7Ya9D79C3+1luNSBIlDFSyRgQAsKhxx5mpQQxy+10+pS6EW1TLJOvvJa1KXTdiSf3aZRe/1B8sVlDNsIVke6G7jqp4KcpfVXZ65gn8EoesBWAFfBxRmRKEegCnXMAUsMzGBRSwKil+4OEegQQBtjCvIiFIKQftqWhAS
  template:
    metadata:
      name: notes-secret
      namespace: dev
    type: Opaque
