apiVersion: v1
kind: Secret
metadata:
  name: notes-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://poweradmin:StrongPassword123!@notes.cav4g2cson71.us-east-1.rds.amazonaws.com:5432/notes"
  DB_SSL: "true"
