---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notes-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgA6sugh3zixfANg9GADIj4PZTJYR61CzbLnCjEmjq9z2+CINnf+2Je51t3VZUuBYSuI+vseiEfIRA6hRpHi6IJnOvBajWANLARf0h2C/OhlA+9OxOapNzwE1tKMfALaqLhxAHgwxruJY92BN+IPZIhCpArsYQ/Se7w0MA46XrRCf7J/8Z2vB6UlBRPNBlkamzwSck+zMR10/B1BtkREtN89v3/9wDqsow1ACcBN8N/7JaRiWrdrTmbmUO9s06cWdypPFIfg2cQfXQT3AUviuxpoIyGZcLeueLFzfOaW3sszlVwXKkftUjE3m7CirrTTV+958CvMzxUaRfCHi7h+OqzT36XcI/mKJLspbkUHjkhjYTQ+wUxa7D7I/DZ3dIvMfnI2lT3vuAHeoGf4yIqb+HtPihqKRZ9q80Hxs2AVsmIo0NbKyYQm9nq4YOYEIMs/Oz12/+RIHM3KkYdmu/9veMVEbdC7/zthOhZPLzPYnTEVwEZIlmW8dnmdistpUVQhaqW6dxyea/K7EYfvm0NW2VHZt5n6GX0BPlxs0RMAbIKaqfe9g5VxKem36oTi/C0nyZSYKrM+6ZPpxJZW4FoGgVZnbzv25uietDBAj7G5AdnJS8za48L4yPDhXKNP4bXBIuBKEIXf/CZg+OIeT4u4Mk6uZVRNZAQ6IIN9QxpWCehBbIYVDRREuYWSnmaQzA2NgQcNW3PqcatQmSwZFHJPWSXslwl4BKIFO1E+X/kHzdjDLqO0sZvKkF1uccIgnYuBML+pv/IP6CnFpX3occOx14KpGBt4a2ocu12eovsYXfZ/je0FdT2Bh5iFPHL8/Dd6LH0Pm7QV
    DB_SSL: AgAni/s2du1W/zz/N1EYwF2nm/O+dIzYv/LwPheLp2fPGBll8QJ5AahQTTQV1GKP9W4wAItM6V/rPPrg+KO8kGjbF+Yn9hXVrEYl1X/aZaNJK3hIbmGFwqsDr34m3B+sfHA0DdsoedaI24TGCT1v0Bkx1sc025eOF+6rU6F3CDV56MipLT+AYnK+Rr5zYc5eyHdkRzu251El3F2pL+ljk5Lg+BUyAwWkzo8C6EOr1CgJJbj9xjw/Hx+wAMRzlaycwneJpRefIRe/ZyBYDNctPHgMPy7UR8wCOCl31jVqQfxP6hhpOUQ9aRtclBScGHzDT6iy7JCiIX9iwSEz2vwNCik61+9/CnOF2BKEKxjs5z8WVeX7jCe0oRBAN3Y1GzB2llpy+OETcG/4cfocsk1os5p5MEHhKPWfmNhHjhx2m1mE/8RyT5U0ddsnQeY0l55GuyzwzMtdDGHGM6cCI5zaKQ11xiCgL5CrXrgXTdvudHUCrJP3EvWc0XjF/NAuBW8gzSjLraAc0x4XiFhwgjbk0ns5sscu5eF2I6+Qo7//jMTpSVsfE99FB1ypjOdzWycVWgSSl1zhpC3wm7vLvzCTCtIoGZbEZbrP4yzOmmrUKoqolpj3qy/GO4MCqeIzSqPxvC8VnCTL4JS8OG9Lu2UBdYVectWVYZFOOVwrLzIFseT54W9Y+TB2bWGlcajgBs6HJUkL+W1p
  template:
    metadata:
      name: notes-secret
      namespace: default
    type: Opaque
