apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-worker
  template:
    metadata:
      labels:
        app: llm-worker
    spec:
      containers:
        - name: llm-worker
          image: REPOSITORY_URI/ECR_WORKER_REPO:1
          envFrom:
            - secretRef:
                name: notes-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
